/** AdvGA / text decklist parsing (Material / Main / Sideboard sections). */

export interface DecklistLine {
  quantity: number;
  name: string;
  section: string;
  /** 1-based line number in the original text. */
  lineNumber: number;
}

export interface ParsedDecklist {
  /** From the first `// Name` comment that isn't a tool banner. */
  title: string;
  lines: DecklistLine[];
  /** Raw section headers encountered, in order. */
  sections: string[];
}

const SECTION_RE = /^#\s*(.+?)\s*$/;
const COMMENT_RE = /^\/\/\s*(.*?)\s*$/;
/** `4 Name`, `4x Name`, `Name x4` */
const QTY_PREFIX_RE = /^(\d+)\s*[x×]\s+(.+)$/i;
const QTY_SPACE_RE = /^(\d+)\s+(.+)$/;
const QTY_SUFFIX_RE = /^(.+?)\s+[x×]\s*(\d+)$/i;

function isToolBanner(comment: string): boolean {
  const t = comment.trim().toLowerCase();
  if (!t) return true;
  return (
    t.startsWith("built with") ||
    t.startsWith("exported from") ||
    t.startsWith("generated by")
  );
}

function parseQuantityName(
  raw: string,
): { quantity: number; name: string } | null {
  const text = raw.trim();
  if (!text) return null;

  let m = text.match(QTY_PREFIX_RE);
  if (m) {
    const quantity = Number(m[1]);
    const name = m[2].trim();
    if (Number.isInteger(quantity) && quantity >= 1 && quantity <= 999 && name) {
      return { quantity, name };
    }
  }

  m = text.match(QTY_SPACE_RE);
  if (m) {
    const quantity = Number(m[1]);
    const name = m[2].trim();
    if (Number.isInteger(quantity) && quantity >= 1 && quantity <= 999 && name) {
      return { quantity, name };
    }
  }

  m = text.match(QTY_SUFFIX_RE);
  if (m) {
    const name = m[1].trim();
    const quantity = Number(m[2]);
    if (Number.isInteger(quantity) && quantity >= 1 && quantity <= 999 && name) {
      return { quantity, name };
    }
  }

  return null;
}

/**
 * Parse an AdvGA-style decklist.
 * Comments (`//`) set the title; `# Section` headers group cards;
 * card lines are `N Name` (also accepts `Nx Name` / `Name xN`).
 */
export function parseDecklist(text: string): ParsedDecklist {
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/);
  let title = "";
  let section = "Main Deck";
  const sections: string[] = [];
  const cardLines: DecklistLine[] = [];

  lines.forEach((raw, index) => {
    const lineNumber = index + 1;
    const trimmed = raw.trim();
    if (!trimmed) return;

    const comment = trimmed.match(COMMENT_RE);
    if (comment) {
      const body = comment[1].trim();
      if (!title && body && !isToolBanner(body)) {
        title = body.slice(0, 40);
      }
      return;
    }

    const sectionMatch = trimmed.match(SECTION_RE);
    if (sectionMatch) {
      section = sectionMatch[1].trim() || "Main Deck";
      if (!sections.includes(section)) sections.push(section);
      return;
    }

    const parsed = parseQuantityName(trimmed);
    if (!parsed) return;
    if (!sections.includes(section)) sections.push(section);
    cardLines.push({
      quantity: parsed.quantity,
      name: parsed.name,
      section,
      lineNumber,
    });
  });

  // Merge duplicate name+section (+ finish later) by summing qty.
  const merged = new Map<string, DecklistLine>();
  for (const row of cardLines) {
    const key = `${row.section.toLowerCase()}::${row.name.toLowerCase()}`;
    const prev = merged.get(key);
    if (prev) {
      merged.set(key, {
        ...prev,
        quantity: Math.min(999, prev.quantity + row.quantity),
      });
    } else {
      merged.set(key, row);
    }
  }

  return {
    title: title || "Imported deck",
    lines: [...merged.values()],
    sections,
  };
}

/** Total cards across all sections. */
export function decklistCardCount(parsed: ParsedDecklist): number {
  return parsed.lines.reduce((sum, row) => sum + row.quantity, 0);
}
