import type { Card } from "./types.js";

export const CARDS: Card[] = [
  {
    id: "ember-sprite",
    name: "Ember Sprite",
    element: "fire",
    rarity: "common",
    cost: 1,
    attack: 2,
    health: 1,
    text: "A flickering spark that darts across the battlefield.",
  },
  {
    id: "inferno-drake",
    name: "Inferno Drake",
    element: "fire",
    rarity: "rare",
    cost: 5,
    attack: 6,
    health: 5,
    text: "When it attacks, deal 1 damage to all enemy minions.",
  },
  {
    id: "phoenix-matriarch",
    name: "Phoenix Matriarch",
    element: "fire",
    rarity: "legendary",
    cost: 8,
    attack: 8,
    health: 8,
    text: "Reborn: returns to your hand the first time it dies.",
  },
  {
    id: "tide-caller",
    name: "Tide Caller",
    element: "water",
    rarity: "common",
    cost: 2,
    attack: 1,
    health: 4,
    text: "Draw a card when this enters play.",
  },
  {
    id: "abyssal-serpent",
    name: "Abyssal Serpent",
    element: "water",
    rarity: "uncommon",
    cost: 4,
    attack: 4,
    health: 4,
    text: "Freeze an enemy minion when this attacks.",
  },
  {
    id: "leviathan-of-the-deep",
    name: "Leviathan of the Deep",
    element: "water",
    rarity: "legendary",
    cost: 9,
    attack: 9,
    health: 10,
    text: "Costs 1 less for each other Water card you have played.",
  },
  {
    id: "mossback-cub",
    name: "Mossback Cub",
    element: "earth",
    rarity: "common",
    cost: 2,
    attack: 3,
    health: 2,
    text: "Taunt. Enemies must attack this minion first.",
  },
  {
    id: "stoneheart-golem",
    name: "Stoneheart Golem",
    element: "earth",
    rarity: "rare",
    cost: 6,
    attack: 5,
    health: 8,
    text: "Taunt. Gains +1 health at the end of your turn.",
  },
  {
    id: "gale-scout",
    name: "Gale Scout",
    element: "air",
    rarity: "common",
    cost: 1,
    attack: 1,
    health: 2,
    text: "Rush. Can attack the turn it is played.",
  },
  {
    id: "storm-herald",
    name: "Storm Herald",
    element: "air",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    health: 3,
    text: "Your other Air minions have +1 attack.",
  },
  {
    id: "arcane-apprentice",
    name: "Arcane Apprentice",
    element: "arcane",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 2,
    text: "Your next spell costs 1 less.",
  },
  {
    id: "chronomancer",
    name: "Chronomancer",
    element: "arcane",
    rarity: "legendary",
    cost: 7,
    attack: 5,
    health: 6,
    text: "At the end of your turn, take an extra turn. Once per game.",
  },
];

export function getCardById(id: string): Card | undefined {
  return CARDS.find((card) => card.id === id);
}
